import sys
import json
import logging
import re
# SCORING order: Gold (20), Silver (17), Bronze (16), 4th (15), 5th (14), 6th (13), 7th (12), 8th (11), 9th (9), 10th (7), 11th (6), 12th (5), 13th (4), 14th (3), 15th (2), 16th (1)
SCORING = [20, 17, 16, 15, 14, 13, 12, 11, 9, 7, 6, 5, 4, 3, 2, 1]

def time_to_sec(t):
    if not t or t == 'NT': return 9999.99
    # Clean non-numeric/colons characters and remove period trailing noise
    val = re.sub(r'[^\d\.:]', '', t).rstrip('.') 
    if not val: return 9999.99
    
    if ':' in val:
        parts = val.split(':')
        # Handle potential for single-digit minutes (e.g., '1:5')
        try:
            minutes = float(parts[0])
            seconds = float(parts[1]) if len(parts) > 1 else 0.0
            return minutes * 60 + seconds
        except ValueError:
            return 9999.99
    try:
        return float(val)
    except ValueError:
        return 9999.99

def calculate_points(athletes):
    """
    Calculates points for all athletes based on rank, round, and event type (individual/relay).
    Assumes input 'athletes' is a list of dictionaries generated by pdf_parser.py.
    """
    # 1. Group athletes by Event and Gender, which is a consistent scoring unit.
    events = {}
    for ath in athletes:
        # Key: (Event Name, Gender)
        key = (ath['event'], ath['gender'])
        if key not in events:
            events[key] = []
        events[key].append(ath)
        
    all_calculated_athletes = {}

    for (event, gender), ev_athletes in events.items():
        is_relay = any(a.get('is_relay') for a in ev_athletes)
        
        # 2. Define sorting logic
        def get_sort_key(a):
            rank = a.get('rank')
            # Rank is the highest priority sort key
            if rank and str(rank).isdigit():
                return (int(rank), 0)
            
            # Fallback sort: Finals time (best performance) -> Prelims time
            t = a.get('finals_time') or a.get('prelims_time')
            return (9999, time_to_sec(t))
            
        if is_relay:
            # --- RELAY POINT CALCULATION ---
            
            # Group relays by team, rank, and round to correctly identify distinct scoring units
            teams = {}
            for a in ev_athletes:
                # We use a composite key for team uniqueness within the event
                t_key = (a['team'], a.get('rank'), a.get('finals_time') or a.get('prelims_time'))
                if t_key not in teams:
                    teams[t_key] = []
                teams[t_key].append(a)
                
            sorted_teams = list(teams.values())
            # Sort teams based on the best swimmer's performance
            sorted_teams.sort(key=lambda team_list: get_sort_key(team_list[0]))
            
            scored_count = 0
            for team_list in sorted_teams:
                team_athlete = team_list[0]
                is_exhibition = team_athlete.get('is_exhibition', False)
                is_time_trial = team_athlete.get('is_time_trial', False) or 'TIME TRIAL' in team_athlete.get('event', '').upper()
                
                # Check if the event round is eligible for points (A/B/Finals)
                is_scoring_round = any(round_name in team_athlete.get('round_swam', '').upper() for round_name in ['A FINAL', 'B FINAL', 'CHAMPIONSHIP FINAL', 'FINALS'])
                can_score = not is_exhibition and not is_time_trial and is_scoring_round
                
                if can_score and scored_count < 16:
                    team_pts = SCORING[scored_count] * 2 # Relay multiplier is always 2x
                    
                    # Distribute points equally among the actual number of swimmers in the team
                    num_swimmers = len(team_list)
                    if num_swimmers == 0: # Should not happen
                        swimmer_pts = 0
                    else:
                        swimmer_pts = team_pts / num_swimmers 
                        
                    for a in team_list:
                        a['calculated_points'] = swimmer_pts
                        all_calculated_athletes[f"{event}_{gender}_{a['name']}"] = a
                    scored_count += 1
                else:
                    for a in team_list:
                        a['calculated_points'] = "N/A"
                        all_calculated_athletes[f"{event}_{gender}_{a['name']}"] = a
        else:
            # --- INDIVIDUAL POINT CALCULATION ---
            
            ev_athletes.sort(key=get_sort_key)
            scored_count = 0
            for ath in ev_athletes:
                is_exhibition = ath.get('is_exhibition', False)
                is_time_trial = ath.get('is_time_trial', False) or 'TIME TRIAL' in ath.get('event', '').upper()
                # Check if the event round is eligible for points
                is_scoring_round = any(round_name in ath.get('round_swam', '').upper() for round_name in ['A FINAL', 'B FINAL', 'CHAMPIONSHIP FINAL', 'FINALS'])
                can_score = not is_exhibition and not is_time_trial and is_scoring_round
                
                if can_score and scored_count < 16:
                    ath['calculated_points'] = SCORING[scored_count]
                    scored_count += 1
                else:
                    ath['calculated_points'] = "N/A"
                
                # Store the calculated points on the athlete object for final output
                all_calculated_athletes[f"{event}_{gender}_{ath['name']}"] = ath
    
    # 3. Compile and return all scored athletes
    return list(all_calculated_athletes.values())

if __name__ == "__main__":
    try:
        input_data = sys.stdin.read()
        if not input_data:
            print(json.dumps({"error": "No input data received."}))
            sys.exit(1)
            
        athletes = json.loads(input_data)
        scored_athletes = calculate_points(athletes)
        print(json.dumps(scored_athletes))
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Failed to parse JSON input: {e}"}))
        sys.exit(1)
    except Exception as e:
        print(json.dumps({"error": f"An unexpected error occurred: {e}"}))
        sys.exit(1)
