import sys
import json
import logging
import re
from collections import defaultdict
# SCORING order: Gold (20), Silver (17), Bronze (16), 4th (15), 5th (14), 6th (13), 7th (12), 8th (11), 9th (9), 10th (7), 11th (6), 12th (5), 13th (4), 14th (3), 15th (2), 16th (1)
DEFAULT_NCAA_D2_SCORING = [20, 17, 16, 15, 14, 13, 12, 11, 9, 7, 6, 5, 4, 3, 2, 1]


def _resolve_scoring_settings(scoring_settings=None):
    if not scoring_settings:
        return {
            'scoringPoints': DEFAULT_NCAA_D2_SCORING,
            'relayMultiplier': 2,
            'halfRateRelaySwimmer': True,
            'maxIndividualScorersPerTeam': 4,
            'maxRelaysScoringPerTeam': 1,
            'maxRosterSize': 18
        }
    # Ensure defaults for missing keys
    cfg = dict(scoring_settings)
    cfg.setdefault('scoringPoints', DEFAULT_NCAA_D2_SCORING)
    cfg.setdefault('relayMultiplier', 2)
    cfg.setdefault('halfRateRelaySwimmer', True)
    cfg.setdefault('maxIndividualScorersPerTeam', 4)
    cfg.setdefault('maxRelaysScoringPerTeam', 1)
    cfg.setdefault('maxRosterSize', 18)
    return cfg


def allowed_rounds_for_conference(conf):
    """Return a set of round name fragments that are considered scoring for the conference.

    - NSISC: A + B finals are scored
    - Default: A, B, C finals are scored (D is unscored)
    """
    if conf and str(conf).upper() == 'NSISC':
        return set(['A FINAL', 'B FINAL', 'CHAMPIONSHIP FINAL', 'FINALS'])
    # Default: explicit finals A/B/C and championship final only. Avoid generic 'FINALS' which
    # can be used as a page header and may cause prelims to be misclassified as scoring.
    return set(['A FINAL', 'B FINAL', 'C FINAL', 'CHAMPIONSHIP FINAL', 'FINALS'])

def time_to_sec(t):
    if not t or t == 'NT': return 9999.99
    # Clean non-numeric/colons characters and remove period trailing noise
    val = re.sub(r'[^\d\.:]', '', t).rstrip('.') 
    if not val: return 9999.99
    
    if ':' in val:
        parts = val.split(':')
        # Handle potential for single-digit minutes (e.g., '1:5')
        try:
            minutes = float(parts[0])
            seconds = float(parts[1]) if len(parts) > 1 else 0.0
            return minutes * 60 + seconds
        except ValueError:
            return 9999.99
    try:
        return float(val)
    except ValueError:
        return 9999.99

def calculate_points(athletes, scoring_settings=None):
    """
    Calculates points for all athletes based on rank, round, and event type (individual/relay).
    Assumes input 'athletes' is a list of dictionaries generated by pdf_parser.py.
    """
    # 1. Group athletes by Event and Gender, which is a consistent scoring unit.
    events = {}
    for ath in athletes:
        # Key: (Event Name, Gender)
        key = (ath['event'], ath['gender'])
        if key not in events:
            events[key] = []
        events[key].append(ath)
        
    all_calculated_athletes = {}

    cfg = _resolve_scoring_settings(scoring_settings)
    SCORING = cfg['scoringPoints']
    relay_multiplier = cfg['relayMultiplier']
    half_rate_relay = cfg['halfRateRelaySwimmer']
    max_relays_cfg = cfg['maxRelaysScoringPerTeam']
    max_individuals_cfg = cfg['maxIndividualScorersPerTeam']

    for (event, gender), ev_athletes in events.items():
        is_relay = any(a.get('is_relay') for a in ev_athletes)
        
        # 2. Define sorting logic
        def get_sort_key(a):
            rank = a.get('rank')
            # Normalize rank: some parsers put asterisk-prefixed ranks in the name field
            def extract_rank(x):
                if not x:
                    return None
                s = str(x)
                m = re.search(r"(\d+)", s)
                return int(m.group(1)) if m else None

            rnum = extract_rank(rank) or extract_rank(a.get('name'))
            # Rank is the highest priority sort key
            if rnum is not None:
                return (int(rnum), 0)

            # Push exhibitions and time-trials to the end regardless of reported time
            if a.get('is_exhibition') or a.get('is_time_trial'):
                t = a.get('finals_time') or a.get('prelims_time')
                return (99999, time_to_sec(t))

            # Fallback sort: Finals time (best performance) -> Prelims time
            t = a.get('finals_time') or a.get('prelims_time')
            return (9999, time_to_sec(t))
            
        if is_relay:
            # --- RELAY POINT CALCULATION ---
            
            # Group relays by team, rank, and round to correctly identify distinct scoring units
            teams = {}
            for a in ev_athletes:
                # We use a composite key for team uniqueness within the event
                t_key = (a['team'], a.get('rank'), a.get('finals_time') or a.get('prelims_time'))
                if t_key not in teams:
                    teams[t_key] = []
                teams[t_key].append(a)
                
            sorted_teams = list(teams.values())
            # Sort teams based on the best swimmer's performance
            sorted_teams.sort(key=lambda team_list: get_sort_key(team_list[0]))
            
            scored_count = 0
            # enforce relay cap per team
            max_relays = max_relays_cfg
            team_relay_count = defaultdict(int)
            i = 0
            while i < len(sorted_teams) and scored_count < 16:
                # build tie group for teams with same rank or same time
                group = [sorted_teams[i]]
                def team_key(tl):
                    ta = tl[0]
                    r = ta.get('rank')
                    t = ta.get('finals_time') or ta.get('prelims_time')
                    return (r, t)
                j = i + 1
                while j < len(sorted_teams) and team_key(sorted_teams[j]) == team_key(sorted_teams[i]):
                    group.append(sorted_teams[j]); j += 1
                # determine points for this group
                team_athlete = group[0][0]
                is_exhibition = team_athlete.get('is_exhibition', False)
                is_time_trial = team_athlete.get('is_time_trial', False) or 'TIME TRIAL' in team_athlete.get('event', '').upper()

                # Determine allowed scoring rounds based on conference heuristics
                conf = team_athlete.get('conference')
                allowed = allowed_rounds_for_conference(conf)
                round_swam_up = team_athlete.get('round_swam', '').upper()
                # If the event is a timed-final/distance race, preliminaries may be the scored heat.
                ev_name = team_athlete.get('event','').upper()
                is_distance = bool(re.search(r'\b(1000|1650|1500|10000|800)\b', ev_name)) or 'TIMED' in ev_name
                is_scoring_round = any(r in round_swam_up for r in allowed) or (is_distance and 'PRELIM' in round_swam_up)
                can_score = not is_exhibition and not is_time_trial and is_scoring_round

                if can_score and scored_count < 16:
                    # compute average points for tied group across positions
                    grp_len = len(group)
                    start = scored_count
                    end = min(scored_count + grp_len, len(SCORING))
                    pts_slice = SCORING[start:end]
                    if pts_slice:
                        avg_point = sum(pts_slice) / len(pts_slice)
                    else:
                        avg_point = 0
                    team_pts_val = avg_point * relay_multiplier
                    # assign team points once per team-event and swimmer-level split per member
                    for team_list in group:
                        team_name = team_list[0].get('team')
                        if team_relay_count[team_name] >= max_relays:
                            for a in team_list:
                                a['calculated_points'] = "N/A"
                                all_calculated_athletes[f"{event}_{gender}_{a['name']}"] = a
                            continue
                        team_relay_count[team_name] += 1
                        num_swimmers = len(team_list)
                        if half_rate_relay:
                            swimmer_pts = team_pts_val / (4.0 if num_swimmers >=4 else num_swimmers)
                        else:
                            swimmer_pts = team_pts_val / num_swimmers if num_swimmers else 0
                        for a in team_list:
                            a['calculated_points'] = swimmer_pts
                            all_calculated_athletes[f"{event}_{gender}_{a['name']}"] = a
                    scored_count += grp_len
                else:
                    for team_list in group:
                        for a in team_list:
                            a['calculated_points'] = "N/A"
                            all_calculated_athletes[f"{event}_{gender}_{a['name']}"] = a
                i = j
                
        else:
            # --- INDIVIDUAL POINT CALCULATION ---
            
            ev_athletes.sort(key=get_sort_key)
            scored_count = 0
            # enforce individual cap per team
            max_individuals = max_individuals_cfg
            team_individual_count = defaultdict(int)
            i = 0
            while i < len(ev_athletes) and scored_count < 16:
                # build tie group
                group = [ev_athletes[i]]
                def indiv_key(a):
                    return (a.get('rank'), a.get('finals_time') or a.get('prelims_time'))
                j = i + 1
                while j < len(ev_athletes) and indiv_key(ev_athletes[j]) == indiv_key(ev_athletes[i]):
                    group.append(ev_athletes[j]); j += 1

                # evaluate scoring eligibility for this group using the first member
                ath = group[0]
                is_exhibition = ath.get('is_exhibition', False)
                is_time_trial = ath.get('is_time_trial', False) or 'TIME TRIAL' in ath.get('event', '').upper()
                # Conference-aware scoring rounds
                conf = ath.get('conference')
                allowed = allowed_rounds_for_conference(conf)
                round_swam_up = ath.get('round_swam', '').upper()
                ev_name = ath.get('event','').upper()
                is_distance = bool(re.search(r'\b(1000|1650|1500|10000|800)\b', ev_name)) or 'TIMED' in ev_name
                is_scoring_round = any(r in round_swam_up for r in allowed) or (is_distance and 'PRELIM' in round_swam_up)
                can_score = not is_exhibition and not is_time_trial and is_scoring_round

                if can_score and scored_count < len(SCORING):
                    grp_len = len(group)
                    start = scored_count
                    end = min(scored_count + grp_len, len(SCORING))
                    pts_slice = SCORING[start:end]
                    if pts_slice:
                        avg_point = sum(pts_slice) / len(pts_slice)
                    else:
                        avg_point = 0
                    for member in group:
                        team_name = member.get('team')
                        if team_individual_count[team_name] >= max_individuals:
                            member['calculated_points'] = 'N/A'
                        else:
                            member['calculated_points'] = avg_point
                            team_individual_count[team_name] += 1
                        all_calculated_athletes[f"{event}_{gender}_{member['name']}"] = member
                    scored_count += grp_len
                else:
                    for member in group:
                        member['calculated_points'] = 'N/A'
                        all_calculated_athletes[f"{event}_{gender}_{member['name']}"] = member
                i = j

    # 3. Compile and return all scored athletes
    return list(all_calculated_athletes.values())

if __name__ == "__main__":
    try:
        input_data = sys.stdin.read()
        if not input_data:
            print(json.dumps({"error": "No input data received."}))
            sys.exit(1)
            
        athletes = json.loads(input_data)
        # Try to load scoring settings written by the server
        scoring_settings = None
        try:
            with open('scoring_settings.json', 'r') as f:
                scoring_settings = json.load(f)
        except Exception:
            scoring_settings = None

        scored_athletes = calculate_points(athletes, scoring_settings)
        print(json.dumps(scored_athletes))
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Failed to parse JSON input: {e}"}))
        sys.exit(1)
    except Exception as e:
        print(json.dumps({"error": f"An unexpected error occurred: {e}"}))
        sys.exit(1)
